---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: flux-system
spec:
  chart:
    spec:
      chart: nginx-stable/nginx-ingress
      sourceRef:
        kind: HelmRepository
        name: nginx
  values:
    controller:
      publishService:
        enabled: true
      metrics:
        enabled: true
  interval: 5m0s
  releaseName: redis
  targetNamespace: default