---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubevious
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kubevious
      sourceRef:
        kind: HelmRepository
        name: kubevious-repo
  interval: 5m0s
  releaseName: kubevious
  targetNamespace: kubevious