apiVersion: spv.no/v1
kind: AzureKeyVaultSecret
metadata:
  name: secret-sync 
  namespace: akv2k8s
spec:
  vault:
    name: gebakv # name of key vault
    object:
      name: cftoken # name of the akv object
      type: secret # akv object type
  output: 
    secret: 
      name: cftoken # kubernetes secret name
      dataKey: values.yaml # key to store object value in kubernetes secret