apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: realtimeapp

resources:
- redis.yaml
- realtime.yaml
- cluster-issuer-production.yaml
- service.yaml
- ingress.yaml
- namespace.yaml


vars:
- name: REDISSERVICE
  objref:
    kind: Service
    name: redis
    apiVersion: v1
- name: REDISNAMESPACE
  objref:
    kind: Service
    name: redis
    apiVersion: v1
  fieldref:
    fieldpath: metadata.namespace