apiVersion: spv.no/v1
kind: AzureKeyVaultSecret
metadata:
  name: secret-sync2 
  namespace: flux-system
spec:
  vault:
    name: gebaprivate # short name of akv
    object:
      name: mysecret # name of the akv object
      type: secret # akv object type
  output: 
    secret: 
      name: mysecret # kubernetes secret name
      dataKey: somekey # key to store object value in kubernetes secret
