apiVersion: spv.no/v1
kind: AzureKeyVaultSecret
metadata:
  name: secret-sync 
  namespace: flux-system
spec:
  vault:
    name: gebakv # short name of akv
    object:
      name: cftoken # name of the akv object
      type: secret # akv object type
  output: 
    secret: 
      name: cftoken # kubernetes secret name
      dataKey: values.yaml # key to store object value in kubernetes secret
